steps:
  # install dependencies
  - name: node:14-slim
    entrypoint: yarn
    args: ["install"]

  # lint checks
  - name: node:14-slim
    entrypoint: yarn
    args: ["lint"]

  # unit tests
  - name: node:14-slim
    entrypoint: yarn
    args: ["test"]

  # build
  - name: node:14-slim
    entrypoint: yarn
    args: ["build"]

  # e2e tests on build
  - name: cypress/base:14
    entrypoint: yarn
    args: ["e2e:ci"]
