steps:
  # install dependencies
  - name: node:14
    entrypoint: yarn
    args: ["install"]

  # run unit tests
  - name: node:14
    entrypoint: yarn
    args: ["test"]

  # build
  - name: node:14
    entrypoint: yarn
    args: ["build"]

  # run e2e tests on build
  - name: node:14
    entrypoint: yarn
    args: ["e2e:ci"]
