name: 'Tests'

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  E2E-Tests:
    name: Run playwright end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Install playwright browsers
        run: npx playwright install chromium --with-deps

      - name: Run tests
        run: npx playwright test
